// Generated by CoffeeScript 1.7.1
(function() {
  var parseFacebookPosts;

  window.app.questions = [];

  app.questions.add = function(rawQuestions) {
    parseFacebookPosts(rawQuestions);
    return console.log({
      questions: app.questions
    });
  };

  parseFacebookPosts = function(posts) {
    var parsed, quizItem, _i, _len, _ref;
    for (_i = 0, _len = posts.length; _i < _len; _i++) {
      quizItem = posts[_i];
      parsed = {};
      parsed.Q = markdown.toHTML(quizItem.message);
      parsed.A = (_ref = quizItem.comments) != null ? _ref.data[0].message : void 0;
      app.questions.push(parsed);
    }
    return app.questions;
  };

}).call(this);
