// Generated by CoffeeScript 1.7.1
(function() {
  var isLoggedIn, loginBtn, onLogIn, onLogOut;

  isLoggedIn = false;

  loginBtn = document.getElementById('FacebookLogin');

  window.fbAsyncInit = function() {
    console.log('facebook ready');
    FB.init({
      appId: window.location.hostname === 'localhost' ? '1538582919703882' : '1538565359705638',
      xfbml: true,
      version: 'v2.0'
    });
    return FB.getLoginStatus(function(response) {
      if (response.status === 'connected') {
        return onLogIn();
      } else {
        return onLogOut();
      }
    });
  };

  loginBtn.onclick = function(evt) {
    evt.preventDefault();
    loginBtn.textContent = '...';
    if (isLoggedIn) {
      return FB.logout(onLogOut);
    } else {
      return FB.login(function(resp) {
        if (resp.authResponse) {
          console.log('Login successful');
          return onLogIn();
        } else {
          console.warn('User cancelled login or did not fully authorize.');
          return onLogOut();
        }
      });
    }
  };

  onLogIn = function() {
    isLoggedIn = true;
    loginBtn.textContent = 'Log Out';
    FB.api('me', function(asdf) {
      return console.log(asdf);
    });
    FB.api('angularjs', function(asdf) {
      return console.log(asdf);
    });
    return FB.api('angularjs/feed', function(asdf) {
      return console.log(asdf);
    });
  };

  onLogOut = function() {
    isLoggedIn = false;
    return loginBtn.textContent = 'Log In';
  };

}).call(this);
