// Generated by CoffeeScript 1.7.1
(function() {
  var body;

  window.app = {
    isLoggedIn: false,
    els: {
      body: body = document.getElementsByTagName('body')[0]
    },
    pages: {},
    init: function() {
      FB.init({
        appId: window.location.hostname === 'localhost' ? '1538582919703882' : '1538565359705638',
        xfbml: true,
        version: 'v2.0'
      });
      return app.showPage('landing');
    },
    showPage: function(pageName) {
      var newPage, _ref;
      body.className = pageName;
      newPage = app.pages[pageName];
      if (typeof (newPage != null ? newPage.show : void 0) === 'function') {
        newPage.show();
        if ((_ref = app.curPage) != null) {
          _ref.hide();
        }
        return app.curPage = newPage;
      } else {
        return console.warn("No show method for page [" + pageName + "]");
      }
    }
  };

  window.dom = {
    hasClass: function(node, className) {
      var idx;
      idx = Array.prototype.indexOf.call(node, className);
      if (idx < 0) {
        return void 0;
      } else {
        return idx;
      }
    },
    removeClass: function(node, className) {
      var idx;
      idx = Array.prototype.indexOf.call(node, className);
      if (idx < 0) {
        return;
      }
      return node.classList.splice(idx, 1);
    }
  };

}).call(this);
