// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(grunt) {
    var cfg;
    require("load-grunt-tasks")(grunt);
    cfg = {
      app: '.',
      tmp: '.tmp'
    };
    grunt.initConfig({
      cfg: cfg,
      express: {
        app: {
          options: {
            port: 3001,
            hostname: "0.0.0.0",
            bases: [__dirname],
            livereload: true
          }
        }
      },
      open: {
        app: {
          path: 'http://localhost:<%= express.app.options.port %>'
        }
      },
      watch: {
        app: {
          options: {
            livereload: true
          },
          files: ["<%= cfg.app %>/*.html", "<%= cfg.app %>/{,*/}*.css", "<%= cfg.app %>/*.js", "<%= cfg.app %>/{,*/}*.js"]
        }
      }
    });
    grunt.registerTask("server", ["express", "open", 'watch']);
    return grunt.registerTask("default", ["server"]);
  };

}).call(this);
