// Generated by CoffeeScript 1.7.1
(function() {
  app.els.logOutBtn = document.getElementById('LogOutBtn');

  app.els.logOutBtn.onclick = function(evt) {
    evt.prevendDefault();
    return FB.logout(onLogOut);
  };

}).call(this);
