// Generated by CoffeeScript 1.7.1
(function() {
  var gotQuizData, onLogIn, onLogOut, thinkingClass;

  app.els.goBtn = document.getElementById('GoButton');

  thinkingClass = 'thinking';

  window.app.pages.landing = {
    show: function() {
      console.log('showing landing page');
      return FB.getLoginStatus(function(response) {
        dom.removeClass(app.els.goBtn, thinkingClass);
        if (response.status === 'connected') {
          return onLogIn();
        } else {
          return onLogOut();
        }
      });
    },
    hide: function() {
      return console.log('hiding landing page');
    }
  };

  app.els.goBtn.onclick = function(evt) {
    evt.preventDefault();
    if (dom.hasClass(app.els.goBtn, thinkingClass)) {
      return;
    }
    if (app.isLoggedIn) {
      return app.showPage('quiz');
    } else {
      Array.prototype.push.call(app.els.goBtn.classList, thinkingClass);
      return FB.login(function(resp) {
        if (resp.authResponse) {
          console.log('Login successful');
          return onLogIn();
        } else {
          console.warn('User cancelled login or did not fully authorize.');
          return onLogOut();
        }
      });
    }
  };

  onLogIn = function() {
    console.log('isLoggedIn', app.isLoggedIn = true);
    app.els.goBtn.textContent = 'Start';
    return FB.api('jsquizzler/statuses', gotQuizData);
  };

  onLogOut = function() {
    console.log('isLoggedIn', app.isLoggedIn = false);
    app.showPage('landing');
    return app.els.goBtn.textContent = 'Log In';
  };

  gotQuizData = function(resp) {
    console.log({
      rawData: resp.data
    });
    return app.questions.add(resp.data);
  };

}).call(this);
