// Generated by CoffeeScript 1.7.1
(function() {
  var buildAnswerButtons, questionIndex, showNextQuestion, showQuestion;

  app.els.skipBtn = document.getElementById('SkipBtn');

  app.els.questions = document.getElementById('Questions');

  app.els.answers = document.getElementById('Answers');

  questionIndex = 0;

  window.app.pages.quiz = {
    show: function() {
      console.log('showing quiz page');
      return showNextQuestion();
    },
    hide: function() {
      return console.log('hiding quiz page');
    }
  };

  app.els.skipBtn.onclick = function(evt) {
    evt.preventDefault();
    return showNextQuestion();
  };

  showNextQuestion = function() {
    showQuestion(questionIndex);
    questionIndex++;
    if (questionIndex === app.questions.length) {
      questionIndex = 0;
    }
    return questionIndex;
  };

  showQuestion = function(idx) {
    app.els.questions.innerHTML = (questionIndex + 1) + ': ' + app.questions[idx].Q;
    app.els.answers.innerHTML = buildAnswerButtons(['true', 'false']);
    return Prism.highlightAll();
  };

  buildAnswerButtons = function(answers) {
    var answer, markup, _i, _len;
    markup = '';
    for (_i = 0, _len = answers.length; _i < _len; _i++) {
      answer = answers[_i];
      markup += "<a class='btn' href='javascript:void(0);'>" + answer + "</a>";
    }
    return markup;
  };

}).call(this);
